-- Small fixture for the mz-graph-queries skill. Generated by
-- evals/mz-graph-queries/build_fixture.py --small; do not edit by hand.
-- Load into any schema: psql ... -f fixture.sql
CREATE TABLE employees (id int NOT NULL, manager_id int, name text NOT NULL, salary int NOT NULL);
CREATE TABLE parts (id int NOT NULL, name text NOT NULL, unit_cost numeric);
CREATE TABLE bom (parent_id int NOT NULL, child_id int NOT NULL, qty int NOT NULL);
CREATE TABLE accounts (id text NOT NULL);
CREATE TABLE transfers (src text NOT NULL, dst text NOT NULL, amount numeric NOT NULL, ts timestamp NOT NULL);
CREATE TABLE groups (id text NOT NULL, parent_id text);
CREATE TABLE memberships (user_id text NOT NULL, group_id text NOT NULL);
CREATE TABLE permissions (group_id text NOT NULL, doc_id text NOT NULL, level text NOT NULL);
CREATE TABLE customers (id text NOT NULL);
CREATE TABLE customer_links (a text NOT NULL, b text NOT NULL, score numeric NOT NULL);
CREATE TABLE cities (id text NOT NULL);
CREATE TABLE roads (src text NOT NULL, dst text NOT NULL, km int NOT NULL);
CREATE TABLE pipelines (id text NOT NULL);
CREATE TABLE depends_on (task text NOT NULL, prereq text NOT NULL);
INSERT INTO employees (id, manager_id, name, salary) VALUES
  (1, NULL, 'Ada', 300),
  (2, 1, 'Bob', 200),
  (3, 1, 'Cy', 190),
  (4, 2, 'Dee', 120),
  (5, 2, 'Eli', 110),
  (6, 3, 'Fay', 100),
  (7, 4, 'Gus', 90),
  (8, 4, 'Hal', 85);
INSERT INTO parts (id, name, unit_cost) VALUES
  (1, 'bike', NULL),
  (2, 'wheel', NULL),
  (3, 'frame', NULL),
  (4, 'spoke', 0.50),
  (5, 'bolt', 0.10),
  (6, 'tire', 20.00);
INSERT INTO bom (parent_id, child_id, qty) VALUES
  (1, 2, 2),
  (1, 3, 1),
  (2, 4, 32),
  (2, 6, 1),
  (2, 5, 4),
  (3, 5, 6);
INSERT INTO accounts (id) VALUES
  ('a1'),
  ('a2'),
  ('a3'),
  ('a4'),
  ('a5'),
  ('a6'),
  ('a7');
INSERT INTO transfers (src, dst, amount, ts) VALUES
  ('a1', 'a2', 100, '2026-01-01 00:01:00'),
  ('a2', 'a3', 50, '2026-01-01 00:02:00'),
  ('a3', 'a1', 25, '2026-01-01 00:03:00'),
  ('a3', 'a4', 10, '2026-01-01 00:04:00'),
  ('a4', 'a5', 5, '2026-01-01 00:05:00'),
  ('a6', 'a7', 7, '2026-01-01 00:06:00');
INSERT INTO groups (id, parent_id) VALUES
  ('g1', NULL),
  ('g2', 'g1'),
  ('g3', 'g2'),
  ('g4', 'g1');
INSERT INTO memberships (user_id, group_id) VALUES
  ('u1', 'g3'),
  ('u2', 'g4'),
  ('u3', 'g2');
INSERT INTO permissions (group_id, doc_id, level) VALUES
  ('g1', 'doc1', 'read'),
  ('g2', 'doc2', 'edit'),
  ('g3', 'doc1', 'edit');
INSERT INTO customers (id) VALUES
  ('c1'),
  ('c2'),
  ('c3'),
  ('c4'),
  ('c5'),
  ('c6'),
  ('c7');
INSERT INTO customer_links (a, b, score) VALUES
  ('c1', 'c2', 0.9),
  ('c2', 'c3', 0.8),
  ('c1', 'c3', 0.95),
  ('c4', 'c5', 0.7),
  ('c5', 'c6', 0.4);
INSERT INTO cities (id) VALUES
  ('A'),
  ('B'),
  ('C'),
  ('D'),
  ('E');
INSERT INTO roads (src, dst, km) VALUES
  ('A', 'B', 4),
  ('B', 'C', 3),
  ('A', 'C', 10),
  ('C', 'D', 2),
  ('B', 'D', 8),
  ('D', 'E', 5);
INSERT INTO pipelines (id) VALUES
  ('raw_orders'),
  ('raw_customers'),
  ('stg_orders'),
  ('stg_customers'),
  ('fct_sales'),
  ('rpt_daily'),
  ('rpt_churn');
INSERT INTO depends_on (task, prereq) VALUES
  ('stg_orders', 'raw_orders'),
  ('stg_customers', 'raw_customers'),
  ('fct_sales', 'stg_orders'),
  ('fct_sales', 'stg_customers'),
  ('rpt_daily', 'fct_sales'),
  ('rpt_churn', 'stg_customers'),
  ('rpt_churn', 'fct_sales');
